config/routes.rb
Rails.application.routes.draw do
  resources :deals

  devise_for :users

  root 'welcome#index'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  def after_sign_in_path_for(sessions)
    deals_path
  end


  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @deals = Deal.all
    respond_with(@deals)
  end

  def show
    respond_with(@deal)
  end

  def new
    @deal = Deal.new
    respond_with(@deal)
  end

  def edit
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.save
    respond_with(@deal)
  end

  def update
    @deal.update(deal_params)
    respond_with(@deal)
  end

  def destroy
    @deal.destroy
    respond_with(@deal)
  end

  private
    def set_deal
      @deal = Deal.find(params[:id])
    end

    def deal_params
      params.require(:deal).permit(:img, :url, :title, :description, :deal_price, :retail_price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="center">
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :deal_price %><br>
    <%= f.text_field :deal_price %>
  </div>
  <div class="field">
    <%= f.label :retail_price %><br>
    <%= f.text_field :retail_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<div class="allCenter">
  <h2 id="tbTitle" >All Deals</h2>
  <p class="new-deal"><%= link_to 'Add a deal', new_deal_path %></p>
  <table class="responsive" data-compression="5" data-min="10" data-max="25" data-width="100%" data-height="100%" data-adjust-parents="true" data-styled="true" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th>Img</th>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>
      <th>Deal Price</th>
      <th>Retail price</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td>
          <img class="dealImg" src="<%= deal.img %>">
        </td>
        <td id="tbtxtwrap"><%=link_to deal.url, "http://#{deal.url}"%></td>
        <td><%= deal.title %></td>
        <td id="tbtxtwrap"><%= deal.description %></td>
        <td><%= "$"+ "#{deal.deal_price}" %></td>
        <td><%= "$"+ "#{deal.retail_price}" %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>

<!-- <span data-tooltip aria-haspopup="true" id="tip" class="has-tip" title=""></span>
 -->

app/views/deals/new.html.erb
<h2>New deal</h2>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img:</strong>
  <%= @deal.img %>
</p>

<p>
  <strong>Url:</strong>
  <%= @deal.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Deal price:</strong>
  <%= @deal.deal_price %>
</p>

<p>
  <strong>Retail price:</strong>
  <%= @deal.retail_price %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

app/views/layouts/_header.html.erb
<nav id="topnav" class="top-bar" data-topbar role="navigation">
  <section class="top-bar-section">
    <span>TierraBarata</span>

    <ul class="right">

      <li class="divider"></li>
        <%- if user_signed_in? %>
          <li ><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
      <li class="divider"></li>
          <li ><%= link_to 'Login', new_user_session_path %></li>
      <li class="divider"></li>
          <li ><%= link_to 'Sign up', new_user_registration_path%></li>
        <% end %>
          </li>
       </li>
     </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>TierraBarata</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

<!--I removed 'http:' from href so browser may decide the correct protocol and fix heroku -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:bold, 400, 800' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <script src="js/vendor/jquery.js"></script>
  <script src="js/foundation/foundation.js"></script>
  <script src="js/foundation/foundation.magellan.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


  </head>

  <body>

<%= render "layouts/header" %>
    <%= yield %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/index.html.erb
<div><%= image_tag("fishing.jpg", :alt => "fishing", :class => "fish", :id =>"rplimg") %></div>